[package]
name = "just_break_out"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
bevy_egui = "0.12"
bevy_asset_loader = "0.9.0"
iyes_loopless = "0.3.0"